# Enable Spark Report
extent.reporter.spark.start=true

extent.reporter.spark.out=test-output/ExtentReport/ExtendReport.html

# Screenshot Configuration
screenshot.dir=test-output/
screenshot.rel.path=../

# System Information
systeminfo.os=Windows
systeminfo.user=Deepak
systeminfo.build=1.0
systeminfo.AppName=Automation Framework
systeminfo.Tester=QA Team

# Base64 Screenshot

# Report Title and Name
extent.reporter.spark.config=src/main/resources/spark-config.xml